<a href="https://colab.research.google.com/github/SayRizz/TensorFlow_Basics/blob/main/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# create constant tensors
scalar = tf.constant(7)
scalar
scalar.ndim

0

In [3]:
vector = tf.constant([10.50])
vector

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.5], dtype=float32)>

In [4]:
vector.ndim

1

In [5]:
matrix = tf.constant([[22,33],[56,44]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 33],
       [56, 44]], dtype=int32)>

In [6]:
matrix.ndim

2

In [7]:
another_matrix = tf.constant([[34.7,7.8],[2.2,4.3],[8.9,6.2]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[34.7,  7.8],
       [ 2.2,  4.3],
       [ 8.9,  6.2]], dtype=float16)>

In [8]:
tensor=tf.constant([[[1,2,3],[4,5,6]],[[2,4,6],[7,9,1]],[[5,3,4],[8,7,3]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 4, 6],
        [7, 9, 1]],

       [[5, 3, 4],
        [8, 7, 3]]], dtype=int32)>

In [9]:
tensor.ndim

3

In [10]:
changeable_tensor=tf.Variable([9,4])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 4], dtype=int32)>

In [11]:
changeable_tensor[0].assign(10)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  4], dtype=int32)>

In [12]:
random_1 = tf.random.Generator.from_seed(45)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.4462975 ]], dtype=float32)>

In [13]:
random_2 = tf.random.Generator.from_seed(45)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.3522796 ,  0.40621263],
       [-1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.4462975 ]], dtype=float32)>

In [14]:
random_3 = tf.random.Generator.from_seed(90)
random_3 = random_3.normal(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.71163535,  0.20890734],
       [-0.25753435, -0.59981036],
       [-1.7857927 ,  0.0044825 ]], dtype=float32)>

In [15]:
shuffle_1 = tf.constant([[2,3],[4,5],[9,0]])
tf.random.shuffle(shuffle_1)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 0],
       [4, 5],
       [2, 3]], dtype=int32)>

In [16]:
tf.random.set_seed(50)
shuffle_1 = tf.constant([[2,3],[4,5],[9,0]])
tf.random.shuffle(shuffle_1, seed=50)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 0],
       [4, 5],
       [2, 3]], dtype=int32)>

In [17]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [18]:
tf.ones([2,4,5])

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [19]:
tf.zeros([4,6])

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
import numpy as np
numpy_1 = np.arange(1,25, dtype=np.int32)
numpy_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A=tf.constant(numpy_1, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [22]:
tensor_attributes = tf.zeros([2,3,4,5])
tensor_attributes

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
print ("Datatype of tensor element is:", tensor_attributes.dtype)
print ("Dimensions of tensor is:", tensor_attributes.ndim)
print ("First axis of tensor is:", tensor_attributes.shape[0])
print ("Last axis of tensor is:", tensor_attributes.shape[-1])
print ("Shape of tensor is:", tensor_attributes.shape)
print ("Size of tensor is:", tf.size(tensor_attributes))
print ("Size of tensor is:", tf.size(tensor_attributes).numpy())
print ("Elements along first axis is:", tensor_attributes[0,1])

Datatype of tensor element is: <dtype: 'float32'>
Dimensions of tensor is: 4
First axis of tensor is: 2
Last axis of tensor is: 5
Shape of tensor is: (2, 3, 4, 5)
Size of tensor is: tf.Tensor(120, shape=(), dtype=int32)
Size of tensor is: 120
Elements along first axis is: tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32)


In [24]:
rank_2_tensor = tf.constant([[2,3],[7,8]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [7, 8]], dtype=int32)>

In [25]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[7],
        [8]]], dtype=int32)>

In [26]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[7],
        [8]]], dtype=int32)>

In [27]:
tensor_operations = tf.constant ([[3,4],[6,7]])
tensor_operations

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [6, 7]], dtype=int32)>

In [28]:
tensor_operations *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [60, 70]], dtype=int32)>

In [29]:
tf.multiply (tensor_operations, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [60, 70]], dtype=int32)>

In [30]:
tensor_operations +20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 24],
       [26, 27]], dtype=int32)>

In [31]:
tensor_operations - 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [32]:
tensor_operations /5

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.6, 0.8],
       [1.2, 1.4]])>

In [33]:
A = tf.constant ([[1,2,3],[5,7,8]])
B = tf.constant ([[2,3],[4,5],[7,1]])

tf.matmul (A,B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 16],
       [94, 58]], dtype=int32)>

In [34]:
X = tf.constant ([[1,4,5],[5,3,2]])
Y = tf.constant ([[4,2],[7,8],[5,6]])

tf.matmul (X,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[57, 64],
       [51, 46]], dtype=int32)>

In [35]:
tf_reshape = tf.constant ([[1,2,3],[4,5,6]])
tf.reshape (tf_reshape, shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [36]:
A1 = tf.constant ([[3,6,8],[8,1,2]])
A2 = tf.constant ([[4,6,7],[1,1,2]])
tf.matmul (A1, tf.reshape(A2, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[62, 40],
       [41, 53]], dtype=int32)>

In [37]:
tf.transpose(X)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 5],
       [4, 3],
       [5, 2]], dtype=int32)>

In [38]:
B = tf.constant ([1.3,4.5])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.3, 4.5], dtype=float32)>,
 tf.float32)

In [39]:
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

In [40]:
E = tf.constant(np.random.randint (0,200, size=100))
E

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([ 34, 195, 170, 162,  31, 178, 183, 143, 142,  28,  67,  81, 179,
        22,  27,  46, 198,  96,  72, 186, 136,   2, 159,   4,  48, 187,
        44,  18,  46,  58,   6,  66, 169, 175, 139, 182, 125, 131, 135,
       169, 194, 107, 163,  41, 177,   1, 179,  91, 181,  92, 148,  54,
        54, 189, 150, 188,  85, 151,  88, 110,  16, 128,  60, 113,  17,
       189,  54, 185,  41, 100, 161,  72,  33,  42, 144, 148,  87, 150,
       143,  12, 142,  32, 150, 144, 199,  88,  52, 176,  89,   3,  10,
       109, 172,  74, 180, 150, 117,   2,  90,  51])>

In [41]:
tf.reshape (E, shape=(2,2,5,5))

<tf.Tensor: shape=(2, 2, 5, 5), dtype=int64, numpy=
array([[[[ 34, 195, 170, 162,  31],
         [178, 183, 143, 142,  28],
         [ 67,  81, 179,  22,  27],
         [ 46, 198,  96,  72, 186],
         [136,   2, 159,   4,  48]],

        [[187,  44,  18,  46,  58],
         [  6,  66, 169, 175, 139],
         [182, 125, 131, 135, 169],
         [194, 107, 163,  41, 177],
         [  1, 179,  91, 181,  92]]],


       [[[148,  54,  54, 189, 150],
         [188,  85, 151,  88, 110],
         [ 16, 128,  60, 113,  17],
         [189,  54, 185,  41, 100],
         [161,  72,  33,  42, 144]],

        [[148,  87, 150, 143,  12],
         [142,  32, 150, 144, 199],
         [ 88,  52, 176,  89,   3],
         [ 10, 109, 172,  74, 180],
         [150, 117,   2,  90,  51]]]])>

In [42]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [43]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=199>

In [44]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=106>

In [45]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=10607>

In [46]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=61.805706>

In [47]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=3819.945>

In [48]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3819>

In [49]:
F = tf.constant(np.random.randint (0,50, size=100))
F

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([ 0, 47, 42, 41, 26,  8, 19, 23,  4, 33, 10, 10, 29, 45, 40, 45, 25,
       18, 30, 34,  1, 10,  2,  4,  8,  9, 42, 31, 19, 19, 14, 33, 18, 42,
       45, 45, 38, 43, 21, 40, 35,  3, 19, 32, 14, 21, 20, 13, 26,  2, 22,
       46, 49, 35, 41, 44, 37, 46,  5, 41, 41,  4, 25, 17, 26, 38, 24, 38,
       21, 39,  6, 13, 38, 22, 40, 32, 19, 40, 40,  0, 19, 42,  6, 25, 17,
       30,  6,  4, 47, 23, 34, 44,  6, 20, 38, 35, 17,  0, 49, 18])>

In [50]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [51]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [52]:
G = tf.constant(np.random.uniform (10,40, size=[1,1,1,1,50]))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float64, numpy=
array([[[[[23.75522635, 10.7304769 , 17.98886867, 10.40570764,
           11.23700347, 33.93852977, 22.53567276, 19.61492329,
           31.73766284, 22.57318033, 15.79484672, 38.50326607,
           39.48945804, 19.74431772, 39.35068084, 23.21057746,
           15.56968875, 15.39057191, 37.0360564 , 29.73629934,
           21.96274073, 15.9315253 , 11.60804263, 28.79918071,
           19.17685583, 28.24697654, 30.21234412, 20.14690129,
           10.56153684, 24.35025303, 16.48696593, 10.12691663,
           36.01126392, 33.37384118, 21.2478026 , 12.25898077,
           29.68381322, 32.08454891, 15.65713635, 38.39351758,
           27.33932039, 32.74091382, 18.34892513, 33.67137092,
           31.17716282, 27.37519373, 12.86246789, 33.44309218,
           34.55167645, 20.30417725]]]]])>

In [53]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [54]:
G_squeezed=tf.squeeze(G)
tf.shape(G_squeezed)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([50], dtype=int32)>

In [55]:
G_squeezed.shape

TensorShape([50])

In [56]:
some_list = [0,1,2,3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [57]:
some_list1 = [0,1,1,0]
tf.one_hot(some_list1, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)>

In [58]:
 tf.one_hot(some_list, depth=4, on_value = "Cricket", off_value="Hockey")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Cricket', b'Hockey', b'Hockey', b'Hockey'],
       [b'Hockey', b'Cricket', b'Hockey', b'Hockey'],
       [b'Hockey', b'Hockey', b'Cricket', b'Hockey'],
       [b'Hockey', b'Hockey', b'Hockey', b'Cricket']], dtype=object)>

In [59]:
H = tf.range(0,12)
H

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [60]:
tf.square(H)

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)>

In [61]:
tf.math.sqrt(tf.cast (H, dtype=tf.float32))

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ,
       2.4494898, 2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166249],
      dtype=float32)>

In [62]:
tf.math.log(tf.cast (H, dtype=tf.float16))

<tf.Tensor: shape=(12,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 , 2.303 , 2.398 ], dtype=float16)>

In [63]:
J = tf.constant(np.array([2,3,4,5,6]))
J

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 5, 6])>

In [64]:
np.array(J)

array([2, 3, 4, 5, 6])

In [65]:
J.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 5, 6])>>

In [66]:
type(J.numpy())

numpy.ndarray